[package]
name = "useless-utils"
license = "MIT"
description = "An extremely useless crate I made for a fun project"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = {version="0.8.5", optional = true}

[features]
default = ["undeterministic"]
undeterministic = ["dep:rand"]
